
name: Build Data Converter

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5 pyyaml lxml

    - name: Build CLI executable
      run: |
        pyinstaller --onefile src/main.py --name data_converter_cli
        if (!(Test-Path -Path "artifacts")) { New-Item -ItemType Directory -Path "artifacts" -Force }
        Copy-Item -Path "dist/data_converter_cli.exe" -Destination "artifacts/" -Force

    - name: Build GUI executable
      run: |
        pyinstaller --onefile --noconsole src/gui.py --name data_converter_gui
        Copy-Item -Path "dist/data_converter_gui.exe" -Destination "artifacts/" -Force

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executables
        path: |
          artifacts/data_converter_cli.exe
          artifacts/data_converter_gui.exe
        retention-days: 7
